[paths]

ventas = /content/Ventas.xlsx
stock  = /content/Stock.xlsx
tiendas = /content/Clasificacion_Tiendas.xlsx
tiempos_entrega = /content/Tiempos de entrega.xlsx


out_dir    = /content/
ventas_out = ventas_procesadas.xlsx
stock_out  = stock_procesado.xlsx
sugerencias_out = Sugerencias_Traslados_Proyecto.xlsx

mode = auto

source = inline

# Puedes pegar en múltiples líneas o separadas por coma
refs_inline = 2485279,2485351,2185326,2485462,2585274,2485325,2585270,
              1185437,2185449,2585353,2585327,2485329,2184989,1485456,
              2485022,1485442,1485464,1185436,2485263,2485348
